Fix Search after review
rusaksenov/homework-react-search pull request #6
Opened 2020-09-23 14:37 UTC by rusaksenov

2020-09-30 16:05 UTC, ilyasidorchik requested changes

2020-09-30 16:05 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +      fetchData()
А вывести алёрт?

2020-09-30 16:05 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +        let response = await fetch(url)
А для `response` почему `let`?

2020-10-05 18:57 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +      let data = fetchData()
Я запустил у себя. Дело в том, что функция `fetchData` возвращает не объект, а промис с объектом.

Так происходит потому что ты сделал функцию асинхронной, а такого типа функции возвращают промис.

А как получить значение из промиса ты уже знаешь :-)

2020-10-07 18:57 UTC, ilyasidorchik requested changes

2020-10-07 18:57 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +      // console.log(data)
Логирование нужно только на этапе разработки. Удали, плз.

2020-10-07 18:57 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +        alert(name + ' - ' + title)
В таком случае лучше шаблонная строка.

2020-10-07 18:57 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +      async function alertData() {
Сделай, пожалуйста, прямо в текущей функции, то есть без создания функции `fetchData`. Это нужно, чтобы я убедился, что ты понял про промисы.

2020-10-07 18:57 UTC, ilyasidorchik commented on src/components/Search/Search.js
>        // alert(name + ' ' + title)
Лишнее

2020-10-08 18:27 UTC, rusaksenov commented on src/components/Search/Search.js
> +      async function alertData() {
Не должно быть присвоения функции или удалить совсем функцию `fetchData`? 
Мне кажется первое.

2020-10-08 18:54 UTC, ilyasidorchik requested changes

2020-10-08 18:54 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +        .then((text) => alert(`${text.name} - ${text.title}`))
У тебя было задание переписать с `then` и `catch` на `async/await` :-)

2020-10-08 18:55 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +        .then((text) => alert(`${text.name} - ${text.title}`))
А так всё ок.

2020-10-09 15:43 UTC, akseonowww commented on src/components/Search/Search.js
> +        .then((text) => alert(`${text.name} - ${text.title}`))
Значит задача решена?

2020-10-09 15:49 UTC, ilyasidorchik commented on src/components/Search/Search.js
> +        .then((text) => alert(`${text.name} - ${text.title}`))
Нет:

> У тебя было задание переписать с then и catch на async/await :-)

2020-10-11 18:42 UTC, ilyasidorchik approved these changes

2020-10-11 19:15 UTC, merged